### ISSUE TITLE
terraform command panics with no args

### ISSUE THREAD

**Issue by ghost** [LMHD/lucli#14]
The Terraform command panics if no arguments are passed, `args[0]` here gives a runtime error: index out of range

https://github.com/LMHD/lucli/blob/2efa0f5ee15c8a55ce063270e668d5d6127c0007/cmd/terraform.go#L53

**Comment by lucymhdavies** [comment]
well spotted

**Comment by lucymhdavies** [comment]
Fix released in [v0.14.1](https://github.com/LMHD/lucli/releases/tag/0.14.1)

**Comment by ghost** [comment]
oh ok, I was going to have a go at fixing this myself.

(grabbing a copy of lucli was easier than installing all the different versions of terraform I need to be using at the moment)

Thanks

**Comment by lucymhdavies** [comment]
It's pretty useful for that, yeah :)
